### ISSUE TITLE
homepage revamp

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/www_old.julialang.org#63] opened 2013-11-11 20:06 UTC
Kicked off by this post: https://groups.google.com/forum/#!topic/julia-dev/pQG6bSglkjc, maybe the home page should get a redesign. This issue is a location for discussion and brainstorming ideas for such a redesign.

**Comment by dpsanders** [comment] 2016-09-14 02:51
Bump. Note that the parallel code
```
nheads = @parallel (+) for i=1:100000000
  int(randbool())
end
```
now actually has two bugs in 0.5!

**Comment by ViralBShah** [comment] 2016-09-14 04:33
Fixed that bug.

**Comment by waldyrious** [comment] 2016-09-14 07:18
> Fixed that bug - rather both.

a387af7 for those wondering.

**Comment by ChrisRackauckas** [comment] 2016-12-13 20:00
Bumping this. Whoever did your JuliaComputing design was really good. You should try to get them to redesign the Julia page as well!

**Comment by StefanKarpinski** [comment] 2016-12-13 22:44
We're planning on it. The content needs a lot of reorganization as well.

**Comment by ViralBShah** [comment] 2016-12-14 06:50
@shashi Can you post your redesign of the julialang front page. We can do the design work separately, but I think shashi got off to a good start.

**Comment by shashi** [comment] 2016-12-14 10:39
sure, it's at http://shashi.github.io/julialang.github.com/

you have to manually rewrite links for now (e.g. Learning is at http://shashi.github.io/julialang.github.com/learning/ and not http://shashi.github.io/learning/)

If someone offers content for the features section of the front page, I will put that in. Do mock up the layout you want to show it with, I can also put that in. All the internal pages basically look as they did before, but in better fonts and stylesheet. Just the new front page needs content.

**Comment by ViralBShah** [comment] 2017-12-18 23:16
We probably should do this for 1.0

**Comment by shashi** [comment] 2017-12-19 06:22
Anyone volunteering to write content for the home page? I'd like to keep the click on feature -> short description + example layout.

**Comment by ViralBShah** [comment] 2017-12-19 16:14
I wonder if we should close this issue, and have a slack #website channel. I wonder if @ChrisRackauckas has some time to brainstorm this. While I think the prototype website has good content, it is not user focussed. It does not convince someone coming why they should use Julia. It may be better to showcase Julia packages front and center along with the language on the landing page, for example.

**Comment by ChrisRackauckas** [comment] 2017-12-23 17:36
## The Constraints

I think this is a difficult issue because the webpage has to stand somewhere in the battle of Julia's identity between a general-purpose programming language and a tool for technical computing. Right now it's an odd hybrid. For example, if you take a look at Rust's homepage:

https://www.rust-lang.org/en-US/

you can see how the top of ours has elements matching that: talk about the language and show some code. If you look at some technical computing tools

https://www.wolfram.com/mathematica/
https://www.mathworks.com/products/matlab.html

it's all about showing plots related to technical computing, which is what we do right after.

Which path we choose depends on the identity that we want Julia to have. However, I think we can choose the technical computing path, but instead make sure we explicitly highlight some examples of general-purpose computing.

One other thing to keep in mind is the sub-communities of "technical computing". There is somewhat of a split in there between scientific computing and data science. Scientific computing is focused on solving differential equations, optimization, and numerical linear algebra. Data science covers statistics, machine learning, and data visualization. These communities have a lot of interplay within Julia but that's quite unique. In reality, most of the time these groups are separated. Usually they are working at different jobs or are in different departments. Even when they are in the same field, they separate themselves by name and application (e.g. in biology you have mathematical biology vs bioinformatics). 

The technical computing focus of Julia with many of its packages and features is amazing for both parties. However, I think that there has been quite a focus on showing off to the data science crowd. And I understand why: data science at around 2013 was booming in popularity and R/Python were taking most of that growth. It's a popular subject with industry pouring lots of money into it. But the scientific computing group is large in academia and national labs. They are in dire need of newer tools as evidenced by how popular Fortran is (with C++ growing) and how MPI is still the most popular HPC tool (this is the crowd that dominates HPC usage).

These two groups have separate but related focuses. Data science communities really care about machine learning frameworks, MCMC tooling, and data handling tooling like DataFrames + MYSQL databases. Scientific computing communities care about parallelization, solving PDEs, 3D plots, and preconditioned Krylov subspace methods for `Ax=b`. They both care about reproducibility and visualization. 

## The Suggestions

So above are the constraints. We need to straddle between general-purpose computing and technical computing, and in technical computing we need to balance between scientific computing and data science. How do we do that?

I think that we can pull inspiration from the Mathematica and MATLAB sites and realize that having a header image is a much more engaging way to show off applications. However, in order to hit our diverse audience we need a sliding display of a few randomized images. Each slide should be a few images composed together with some simple text next to it. Given the above analysis, I think we need to hit a few points:

1. A quick example showing a picture of code in an IDE showing off some programming language features (multiple dispatch, metaprogramming) for the general-purpose crowd.
2. A general purpose application. Maybe some web server with Julia code and the site shown. Genie.jl or Escher.jl? Web applications are of growing importance in technical computing so that has nice crossover.
3. A machine learning framework application. I think a nice simple code from @MikeInnes's Flux.jl showing a picture of the net and some visualization of the output. Maybe doing image segmentation and/or detection. The code should, if simple enough, pull from some database to show off that stuff to the general-purpose crowd at the same time.
4. A PDE. Of the scientific computing applications, this one is nice to pull from because you get to show off some really beautiful 3D graphics which data science people could be interested in as well.
5. A picture of some servers with astronomers and happy scientists. This slide is about high performance computing. Mention Julia's speed, Celeste's petascale application, parallelism and GPU support. This is a crowd pleaser to all of the groups.

Below those 5 images, I think that MATLAB's site has a good setup of doing a picture with each quick explanation. I think it should go like this:

1. The first section has to be about the language. On the left, a good picture for this is the Julia benchmark: let it and its caption which links to a separate benchmark page explain itself. On the right the summary of language features, maybe pruned a little bit. Put the part about the license in here: the people who focus on this part are the people who care about licenses.
2. In the next part, I think we can be more succinct. "Designed for fast and reproducible scientific applications". The image should show off code inside of IJulia, and again have some nice visualizations. I think it should show off simple calls but do something in parallel. Maybe a parallel Monte Carlo calculation of something like pi with a picture of the dots with a circle?
3. Section 3 should be about packages. The "image" should instead be the randomized Youtube videos of JuliaCon. It should link to JuliaObserver.com, which has been an unofficial but amazing package search engine that we should highlight more. Then the text should highlight some of the popular packages with one blurb about what they do. Probably, instead of separating by packages, separate by topic. So it should be like:

- Plotting and visualization: Gadfly.jl, Plots.jl, PyPlot.jl
- Neural networks: KNet.jl, MXNet.jl, Flux.jl, TensorFlow.jl
- Statistics: GLM.jl, Distributions.jl, MultivariateStatistics.jl
- Data Handling: Dataframes.jl, JLD2.jl, ODBC.jl
- Optimization: JuMP.jl, Optim.jl
- Differential Equations: DifferentialEquations.jl
- Numerical Linear Algebra: PETSc.jl, IterativeSolvers.jl
- Parallelization: MPI.jl, DistributedArrays.jl, ParallelAccelerator.jl

I think that covers a wide range of technical computing? Each of the names should be a link to send the potential user directly to the packages. This answers the vast majority of "does Julia have ___?" that the audience usually asks.

There is a tough balance here between "not wanting to pick winners" in an open source community, but also we want to show some stuff off! So I am considering a general rule would be to pick and order packages by star count as much as possible as a reasonable indicator of popularity and overall impact. And the list can always be changed in the future (and this was only preliminary, feel free to bikeshed that list like crazy).

And I think that's it. I don't think it should go further than 3 sections. Maybe a 4th one showing off an interactive REPL if we have one for the web.

## Summary

We need to hit general computing, data science, and scientific computing. I think we do this by 

- Having a sliding image at the top show off some nice visualizations in a way that is "cross-field" (but still with a focus on each one)
- Then 3 sections on the language, then science (reproducibility, since everyone in the field cares about that), then packages. 

Each section has a corresponding visualization to catch the eye. Some core parts of this design is:

1. Hit all of the high level parts of data science and scientific computing, but whenever we do so, show off something that is usable to other communities. So we need to show solving a PDE, but show off 3D graphics and parallelization at the same time. We need to show off neural networks, so show off database handling and GPU support at the same time. We need to show that we are still a general purpose language, so show off a general purpose application that scientists care about like web apps.
2. We don't need to discuss much about the visualization packages and IDEs. Instead, it can just be implicit in the pictures that we show. We can show off Julia code in Juno, make our visualizations with Plots.jl and Gadfly.jl, and show IJulia by showing off code that has ran inside of it.
3. The benchmarks are right front and center, but "language features" is just the first point. The features of Julia are its language, its scientific community, and its packages. I think this setup weaves them together well and flows quickly enough to packages.
4. Showing off Julia by showing off its community tools. Instead of plain code and features, code is in nice IDEs and using packages to make things succinct. We give direct links to things like JuliaObserver to let potential users explore what the community has to offer, along with highlighting a few that are of common interest to people who generally look into Julia.
5. It's colorful and inviting. Every piece of text has an image. Text can be minimized to small lists, and extra details are behind links for those who are interested. 

Of course, this is just my idea/explanations so I am curious to hear what others think. Building these images will be the toughest part, but I think image-based websites look much more modern and inviting than something that is text-heavy.

**Comment by shashi** [comment] 2017-12-27 15:27
@ChrisRackauckas Love your thoughtful comments! I agree that it's difficult yet important to resolve what identity of Julia we would like to convey on the front page. Focusing on one may dilute the others. But I think your plan strikes a good balance.

I could prototype the layout for this page as you described it and circulate, do you think you can help me with the images and verbiage?

Cheers!

**Comment by ChrisRackauckas** [comment] 2017-12-27 15:33
Yeah, if you're willing to prototype lets get the community together! I can help get some of the Julia visualizations, but I will say my editing skills are bad so I can't really compose them together well. Let's pull in @MikeInnes @Evizero (you make good figures 👍 ) @mkborregaard @tlnagy and see if any of them have concrete ideas for figures.

**Comment by Dmitrii-I** [comment] 2017-12-29 08:26
On https://julialang.org/ there is a screenshot https://julialang.org/images/ijulia.png containing code

```
using RDatasets
using Gadfly
set_default_plot_size(9inch, 9inch/golden)
plot(data("datasets", "iris"), x="Sepal.Width", y="Sepal.Length", color="Species")
```

Running this code in 0.6.2 results in error:

```
MethodError: no method matching data(::String, ::String)

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
```

**Comment by nalimilan** [comment] 2017-12-29 10:27
Indeed. Looks like we need to replace `data` with `dataset`.

**Comment by mkborregaard** [comment] 2017-12-30 11:49
👍 to @ChrisRackauckas ' ideas (except I don't think data science has gotten too much of the attention :-) ). Should we brainstorm ideas on Slack or in this thread? Figures - I think we need a basic non-fancy multipanel figure with a scatter plot with error bars and a trendline, and a barplot, to signal "yes julia is useful for your daily pedestrian work) and nice shaded 3D visualization with Makie to demonstrate the scope.

**Comment by StefanKarpinski** [comment] 2018-01-04 16:46
Some notes from a quick call discussing some redesign ideas based on @ChrisRackauckas's post:

1. Top: simple, general Julia code examples
    1. some computation
    2. some visualization
    3. IDEs with code + images
    4. neural nets stuff (for the hype)
2. Download links on the right
    1. large “Download”  button autodetects correct download
    2. small “other versions” link to go to downloads page
3. Below the fold: grid of Julia domains
    1. click-through to targeted examples
    2. links to relevant community forum, docs, etc.
    3. below that some high-level performance/functionality comparisons

Need some space for announcements at the very top, perhaps videos too?

Have “domains” subpage with all domains
- List the really popular & solid domains on landing page
- Some thoughts on possible curated home-page domains:
    1. JuliaOpt
    2. DifferentialEquations
    3. Numerical Linear Algebra
    4. Statistics
    5. Data Analysis
    6. Deep Learning
    7. Images & Visualization
    8. GPUs (when ready)

Different target audiences?
- Coming from R, Python, Matlab
- Targeted performance comparison
- Relevant packages that you might want
- Some useful tips and pointers
- Links to more info, e.g. tags on Discourse

Like Shashi’s row of videos
- could we expand and autoplay on mouse hover? or is that too obnoxious

**Comment by crstnbr** [comment] 2018-03-18 08:25
I highly appreciate the ideas in this thread and would be willing to contribute within my capabilities if this makes sense. Where is the communication for this redesign happening? I couldn't find a #website channel on slack.

FWIW, a minor point that I observed when reading the above. I feel that the domain/topics lists above seem to focus on more abstract disciplines like general math disciplines, computer science and generic things like plotting. I, of course, agree that this should be the main focus as it basically allows you to do anything else, but to inspire new scientists maybe more specific science domains should also be mentioned/showcased. BioJulia in Stefan's list seems to be the only mention in this direction. What about the other natural sciences and the finance branch of Julia? (I'm a physicist and would be most likely be caught be showing some physics application).

**Comment by ViralBShah** [comment] 2018-08-03 01:48
Done. The new website is live at www.julialang.org.

**Closed by ViralBShah** 2018-08-03 01:48 UTC
